# Generated by Django 4.1.2 on 2023-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("current_floor", models.IntegerField(default=0)),
                (
                    "direction",
                    models.CharField(blank=True, default=None, max_length=4, null=True),
                ),
                ("floor_to", models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_floors", models.IntegerField()),
                ("time_taken_between_floors", models.IntegerField()),
            ],
        ),
    ]
