# Generated by Django 4.1.2 on 2023-11-09 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("elevator_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="time_taken_between_floors",
            new_name="number_of_elevators",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="floor_to",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="id",
        ),
        migrations.AlterField(
            model_name="elevator",
            name="number",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="ElevatorJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("floor_from", models.IntegerField()),
                ("floor_to", models.IntegerField()),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 9, 12, 2, 3, 421179)
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator_panel.elevator",
                    ),
                ),
            ],
        ),
    ]
